### ISSUE TITLE
Run as XSLT process or as DITA-OT plugin?

### ISSUE THREAD

**Issue by sethpark** [dita-community/doxygen2dita#2]
Thanks for this work, Eliot. I'm doing a quick and dirty feasibility study. I dont see a way to run doxygen2dita using standard DITA-OT methods, so I'm running the XSLT from oXygen XSLT Debugger perspective. I'm seeing issues with undefined "outdir" variables. Since I'm in quick-and-dirty mode, I'm hardcoding these variables as needed.

What is the intended method for running this plugin? As an XSLT task or as a DITA-OT plugin?

**Comment by drmacro** [comment]
Right now you just apply it to the Doxygen-generated XML file directly using a normal XSLT scenario. You must specify the outdir parameter.

If you use a normal XSLT transformation scenario the scenario dialog will show you the parameters that need to be run.

**Comment by drmacro** [comment]
This is how I have the outdir parameter set in my Oxygen transform scenario:

`${cfdu}/../dita`

**Comment by drmacro** [comment]
The input is the index.xml file from Doxygen

**Comment by sethpark** [comment]
Perfect. Thanks.
